	[[module.entry]]
	name = "UPDWMIX"
	uuid = "42F8060C-832F-4DBF-B247-51E961997B34"
	affinity_mask = "0x1"
	instance_count = "15"
	domain_types = "0"
	load_type = "0"
	module_type = "5"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xffff, 0xc, 0x8, 0x05ff,
			1, 0, 0xffff, 0xc, 0x8, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [1, 0, 0, 0, 216, 5044000, 384, 192, 0, 5044, 0,
			2, 0, 0, 0, 216, 2660000, 384, 384, 0, 2660, 0,
			3, 0, 0, 0, 216, 3164000, 576, 384, 0, 3164, 0,
			4, 0, 0, 0, 216, 3316000, 768, 384, 0, 3316, 0,
			5, 0, 0, 0, 216, 5264000, 768, 384, 0, 5264, 0,
			6, 0, 0, 0, 216, 5440000, 768, 384, 0, 5440, 0,
			7, 0, 0, 0, 216, 2888000, 768, 192, 0, 2888, 0,
			8, 0, 0, 0, 216, 2856000, 768, 192, 0, 2856, 0,
			9, 0, 0, 0, 216, 2876000, 768, 192, 0, 2876, 0,
			10, 0, 0, 0, 216, 2956000, 960, 192, 0, 2956, 0,
			11, 0, 0, 0, 216, 2888000, 1152, 192, 0, 2888, 0,
			12, 0, 0, 0, 216, 2888000, 1152, 192, 0, 2888, 0,
			13, 0, 0, 0, 216, 2816000, 1536, 192, 0, 2816, 0,
			14, 0, 0, 0, 216, 2468000, 192, 384, 0, 2468, 0,
			15, 0, 0, 0, 216, 3084000, 576, 384, 0, 3084, 0,
			16, 0, 0, 0, 216, 3442000, 960, 384, 0, 3442, 0,
			17, 0, 0, 0, 216, 3478000, 1152, 384, 0, 3478, 0,
			18, 0, 0, 0, 216, 3478000, 1152, 384, 0, 3478, 0,
			19, 0, 0, 0, 216, 3736000, 1536, 384, 0, 3736, 0,
			20, 0, 0, 0, 216, 3216000, 192, 1152, 0, 3216, 0,
			21, 0, 0, 0, 216, 3308000, 384, 1152, 0, 3308, 0,
			22, 0, 0, 0, 216, 3616000, 768, 1152, 0, 3616, 0,
			23, 0, 0, 0, 216, 3616000, 768, 1152, 0, 3616, 0,
			24, 0, 0, 0, 216, 4916000, 1536, 1152, 0, 4916, 0,
			25, 0, 0, 0, 216, 3228000, 192, 1152, 0, 3228, 0,
			26, 0, 0, 0, 216, 3452000, 384, 1152, 0, 3452, 0,
			27, 0, 0, 0, 216, 4016000, 768, 1152, 0, 4016, 0,
			28, 0, 0, 0, 216, 5080000, 1536, 1152, 0, 5080, 0,
			29, 0, 0, 0, 216, 3552000, 384, 1536, 0, 3552, 0,
			30, 0, 0, 0, 216, 3728000, 768, 1152, 0, 3728, 0]

	index = __COUNTER__
