	REM # Cadence module config
	[[module.entry]]
	name = "CADENCE"
	uuid = "D8218443-5FF3-4A4C-B388-6CFE07B956AA"
	affinity_mask = "0x3"
	instance_count = "1"
	domain_types = "0"
	load_type = "0"
	init_config = "1"
	module_type = "31"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xa, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [0, 0, 0, 0, 4096, 1000000, 128, 128, 0, 0, 0]

	index = __COUNTER__
