sudo: required

language: c

git:
  depth: false

services:
  - docker
stages:
  - compile
  - test
  - deploy

before_install:
  - docker pull xiulipan/sof && docker tag xiulipan/sof sof
  - docker pull xiulipan/sofqemu && docker tag xiulipan/sofqemu sofqemu

jobs:
  include:
    - stage: compile
      name: "Tools Build"
      script: ./scripts/docker-run.sh ./scripts/build-tools.sh
    - stage: compile
      name: "BYT Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l byt
    - stage: compile
      name: "CHT Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cht
    - stage: compile
      name: "BDW Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l bdw
    - stage: compile
      name: "HSW Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l hsw
    - stage: compile
      name: "APL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l apl
    - stage: compile
      name: "CNL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cnl
    - stage: compile
      name: "SUE Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l sue
    - stage: compile
      name: "ICL Build"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l icl
    - stage: compile
      name: "Host Build"
      script: ./scripts/docker-run.sh ./scripts/host-build-all.sh -l
    - stage: test
      name: "BYT Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l byt && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh byt
    - stage: test
      name: "CHT Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l cht && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh cht
    - stage: test
      name: "BDW Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l bdw && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh bdw
    - stage: test
      name: "HSW Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l hsw && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh hsw
    - stage: test
      name: "APL Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l -r apl && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh apl
    - stage: test
      name: "SKL Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l -r skl && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh skl
    - stage: test
      name: "KBL Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l -r kbl && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh kbl
    - stage: test
      name: "CNL Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l -r cnl && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh cnl
    - stage: test
      name: "ICL Boot Test"
      script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -l -r icl && ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh icl
