sudo: required

language: c

git:
  depth: false

services:
  - docker
stages:
  - test
  - qemutest

before_install:
  - docker pull thesofproject/sof && docker tag thesofproject/sof sof

env:
  - PLATFORM=byt
  - PLATFORM=cht
  - PLATFORM=bdw
  - PLATFORM=hsw
  - PLATFORM=apl
  - PLATFORM=skl
  - PLATFORM=kbl
  - PLATFORM=cnl
  - PLATFORM=sue
  - PLATFORM=icl
  - PLATFORM=jsl
  - PLATFORM=imx8
  - PLATFORM=imx8x
  - PLATFORM=imx8m

script: ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -j $PLATFORM

jobs:
  include:
    - stage: test
      script: ./scripts/docker-run.sh ./scripts/build-tools.sh
      env: PLATFORM=tools
    - stage: test
      script: ./scripts/docker-run.sh ./scripts/host-build-all.sh -l
      env: PLATFORM=host
      # Matrix hack: Declare the same stage name multiple times to test multiple
      # versions. Use a YAML alias to prevent redundancy.
    - &qemuboottest
      stage: qemutest
      script:
        - sed -i $(($(grep "config HAVE_AGENT" -n src/platform/Kconfig | cut -f1 -d:)+2))"s/default y/default n/" src/platform/Kconfig
        - ./scripts/docker-run.sh ./scripts/xtensa-build-all.sh -r -j $PLATFORM
        - ./scripts/docker-qemu.sh ../sof.git/scripts/qemu-check.sh $PLATFORM
      env: PLATFORM=byt
      before_install:
        - docker pull thesofproject/sof && docker tag thesofproject/sof sof
        - docker pull thesofproject/sofqemu && docker tag thesofproject/sofqemu sofqemu
    - <<: *qemuboottest
      env: PLATFORM=cht
    - <<: *qemuboottest
      env: PLATFORM=bdw
    - <<: *qemuboottest
      env: PLATFORM=hsw
    - <<: *qemuboottest
      env: PLATFORM=apl
    - <<: *qemuboottest
      env: PLATFORM=skl
    - <<: *qemuboottest
      env: PLATFORM=kbl
    - <<: *qemuboottest
      env: PLATFORM=cnl
    - <<: *qemuboottest
      env: PLATFORM=icl
    - <<: *qemuboottest
      env: PLATFORM=imx8
    - <<: *qemuboottest
      env: PLATFORM=imx8x
