	[[module.entry]]
	name = "COPIER"
	uuid = "9BA00C83-CA12-4A83-943C-1FA2E82F9DDA"
	affinity_mask = "0x1"
	instance_count = "32"
	domain_types = "0"
	load_type = "0"
	module_type = "3"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xf, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xf, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xf, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xf, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xf, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
#if CONFIG_METEORLAKE
	mod_cfg = [1, 0, 0, 0, 280, 4918000, 768, 768, 0, 4918, 0,
			2, 0, 0, 0, 280, 6526000, 768, 768, 0, 6526, 0,
			3, 0, 0, 0, 280, 6388000, 384, 384, 0, 6388, 0,
			4, 0, 0, 0, 280, 4682000, 512, 512, 0, 4682, 0,
			5, 0, 0, 0, 280, 5738000, 512, 512, 0, 5738, 0,
			6, 0, 0, 0, 280, 6250000, 256, 256, 0, 6250, 0,
			7, 0, 0, 0, 280, 6460000, 768, 768, 0, 6460, 0,
			8, 0, 0, 0, 280, 7116000, 768, 768, 0, 7116, 0,
			9, 0, 0, 0, 280, 6008000, 384, 384, 0, 6008, 0,
			10, 0, 0, 0, 280, 6258000, 512, 512, 0, 6258, 0,
			11, 0, 0, 0, 280, 7188000, 1024, 1024, 0, 7188, 0,
			12, 0, 0, 0, 280, 7272000, 1536, 1536, 0, 7272, 0,
			13, 0, 0, 0, 280, 6290000, 768, 768, 0, 6290, 0,
			14, 0, 0, 0, 280, 6604000, 1024, 1024, 0, 6604, 0,
			15, 0, 0, 0, 280, 6198000, 384, 384, 0, 6198, 0,
			16, 0, 0, 0, 280, 6250000, 384, 384, 0, 6250, 0,
			17, 0, 0, 0, 280, 6258000, 256, 256, 0, 6258, 0,
			18, 0, 0, 0, 280, 4354000, 256, 256, 0, 4354, 0,
			19, 0, 0, 0, 280, 6198000, 256, 256, 0, 6198, 0,
			20, 0, 0, 0, 280, 6250000, 128, 128, 0, 6250, 0,
			21, 0, 0, 0, 280, 6250000, 128, 128, 0, 6250, 0,
			22, 0, 0, 0, 280, 6206000, 128, 128, 0, 6206, 0,
			23, 0, 0, 0, 280, 4170000, 64, 64, 0, 4170, 0,
			24, 0, 0, 0, 280, 4234000, 96, 96, 0, 4234, 0,
			25, 0, 0, 0, 280, 6198000, 96, 96, 0, 6198, 0,
			26, 0, 0, 0, 280, 6250000, 96, 96, 0, 6250, 0,
			27, 0, 0, 0, 280, 6198000, 192, 192, 0, 6198, 0,
			28, 0, 0, 0, 280, 6258000, 192, 192, 0, 6258, 0,
			29, 0, 0, 0, 280, 6392000, 720, 720, 0, 6392, 0,
			30, 0, 0, 0, 280, 6250000, 360, 360, 0, 6250, 0,
			31, 0, 0, 0, 280, 5326000, 360, 360, 0, 5326, 0,
			32, 0, 0, 0, 280, 6258000, 180, 180, 0, 6258, 0,
			33, 0, 0, 0, 280, 4354000, 256, 256, 0, 4354, 0,
			34, 0, 0, 0, 280, 4898000, 256, 256, 0, 4898, 0,
			35, 0, 0, 0, 280, 6246000, 128, 128, 0, 6246, 0,
			36, 0, 0, 0, 280, 6250000, 192, 192, 0, 6250, 0,
			37, 0, 0, 0, 280, 6250000, 48, 48, 0, 6250, 0,
			38, 0, 0, 0, 280, 4170000, 64, 64, 0, 4170, 0,
			39, 0, 0, 0, 280, 6198000, 64, 64, 0, 6198, 0,
			40, 0, 0, 0, 280, 6246000, 32, 32, 0, 6246, 0,
			41, 0, 0, 0, 280, 5272000, 192, 384, 0, 5272, 0,
			42, 0, 0, 0, 280, 5350000, 384, 192, 0, 5350, 0]
#elif CONFIG_LUNARLAKE
	mod_cfg = [ 0, 0, 0, 0, 280, 640100, 45, 60, 0, 0, 0,
			1, 0, 0, 0, 280, 1106300, 192, 192, 0, 0, 0,
			2, 0, 0, 0, 280, 1573000, 45, 45, 0, 0, 0,
			3, 0, 0, 0, 280, 2040600, 192, 256, 0, 0, 0,
			4, 0, 0, 0, 280, 2507500, 192, 256, 0, 0, 0,
			5, 0, 0, 0, 280, 2999000, 192, 256, 0, 0, 0,
			6, 0, 0, 0, 280, 3501000, 45, 60, 0, 0, 0,
			7, 0, 0, 0, 280, 3927000, 192, 256, 0, 0, 0,
			8, 0, 0, 0, 280, 4424000, 192, 256, 0, 0, 0,
			9, 0, 0, 0, 280, 4941000, 192, 256, 0, 0, 0]
#endif

	index = __COUNTER__
