#ifndef LOAD_TYPE
#define LOAD_TYPE "0"
#endif

	REM # eq iir module config
	[[module.entry]]
	name = "EQIIR"
	uuid = "5150C0E6-27F9-4EC8-8351-C705B642D12F"
	affinity_mask = "0x1"
	instance_count = "40"
	domain_types = "0"
	load_type = LOAD_TYPE
	module_type = "9"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xf, 0x45ff,
		1, 0, 0xfeef, 0xf, 0xf, 0x1ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
#if CONFIG_METEORLAKE
	mod_cfg = [0, 0, 0, 0, 4096, 1000000, 128, 128, 0, 1000, 0,
			0, 0, 0, 0, 4096, 20663000, 768, 768, 0, 20663, 0,
			0, 0, 0, 0, 4096, 11357000, 384, 384, 0, 11357, 0]
#elif defined(CONFIG_LUNARLAKE) || defined(CONFIG_PANTHERLAKE)
	mod_cfg = [0, 0, 0, 0, 4096, 1000000, 128, 128, 0, 0, 0]
#endif

	index = __COUNTER__
