version = [1, 0]  # use simple file write

[adsp]
name = "acp_7_0"

[[adsp.mem_zone]]
type = "IRAM"
base = "0x7F000000"
size = "0x60000"
host_offset = "0x0"
[[adsp.mem_zone]]
type = "DRAM"
base = "0xE0000000"
size = "0x20000"
host_offset = "0x0"
[[adsp.mem_zone]]
type = "SRAM"
base = "0x6000C000"
size = "0x274000"
host_offset = "0x0"